name: 'Checkout'
description: 'Checkout a Git repository at a particular version'
runs:
  using: 'composite'
  steps:
    - name: 'Print malicious world'
      shell: bash
      run: echo 'malicious world'
